import { Roadmap, Agent, Project, Resource, Progress, Task } from '../types';

export const MOCK_USER = {
  id: '987f6543-e21b-34c5-d678-098765432100',
  email: 'arjun.developer@example.com',
};

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'agent_goal',
    name: 'Goal Analyzer Agent',
    icon: 'Target',
    role_description: 'Validates target scope, difficulty limits, and estimates initial timescales.',
    status: 'done',
  },
  {
    id: 'agent_curriculum',
    name: 'Curriculum Agent',
    icon: 'BookOpen',
    role_description: 'Constructs sequential curriculum milestones and maps learning modules.',
    status: 'done',
  },
  {
    id: 'agent_planner',
    name: 'Daily Planner Agent',
    icon: 'Calendar',
    role_description: 'Schedules specific day-by-day learning task allocations based on hours.',
    status: 'done',
  },
  {
    id: 'agent_resource',
    name: 'Resource Finder Agent',
    icon: 'Search',
    role_description: 'Queries verified platforms for documentation guides and videos.',
    status: 'done',
  },
  {
    id: 'agent_project',
    name: 'Project Mentor Agent',
    icon: 'Hammer',
    role_description: 'Architects real-world capstone assignments with Socratic chat aids.',
    status: 'done',
  },
  {
    id: 'agent_quiz',
    name: 'Quiz Master Agent',
    icon: 'HelpCircle',
    role_description: 'Compiles topic-specific multiple-choice validation tests.',
    status: 'done',
  },
  {
    id: 'agent_career',
    name: 'Career Agent',
    icon: 'Briefcase',
    role_description: 'Matches goals to hireability specs, resume lines, and interview mocks.',
    status: 'done',
  },
];

export const MOCK_ROADMAP: Roadmap = {
  id: '550e8400-e29b-41d4-a716-446655440000',
  user_id: MOCK_USER.id,
  profile_id: 'profile_123',
  title: 'Full-Stack TypeScript Backend Architect',
  total_weeks: 6,
  start_date: '2026-07-17',
  end_date: '2026-08-28',
  status: 'active',
  milestones: [
    {
      id: 'mile_1',
      user_id: MOCK_USER.id,
      roadmap_id: '550e8400-e29b-41d4-a716-446655440000',
      sequence_number: 1,
      title: 'Structural Architecture & Compiler Setup',
      description: 'Master strict TypeScript compilation flags, project structure layouts, and node compiler tools.',
      estimated_days: 7,
      topics: ['NPM Workspace', 'tsconfig configurations', 'Strict check triggers', 'Module systems'],
      learning_objectives: ['Initialize Node directories', 'Configure package workspaces', 'Build modules compilation workflows'],
      status: 'completed',
      started_at: '2026-07-10T08:00:00Z',
      completed_at: '2026-07-16T18:00:00Z',
    },
    {
      id: 'mile_2',
      user_id: MOCK_USER.id,
      roadmap_id: '550e8400-e29b-41d4-a716-446655440000',
      sequence_number: 2,
      title: 'Express APIs with Schema Validations',
      description: 'Develop structured Express router paths integrated with controller handlers and body object validations using Zod.',
      estimated_days: 7,
      topics: ['Express Middleware pipelines', 'Controller patterns', 'Zod request validation schema', 'Async helper wrappers'],
      learning_objectives: ['Code custom Express error handles', 'Validate HTTP request parameters', 'Construct standard JSON endpoints'],
      status: 'in_progress',
      started_at: '2026-07-17T08:00:00Z',
    },
    {
      id: 'mile_3',
      user_id: MOCK_USER.id,
      roadmap_id: '550e8400-e29b-41d4-a716-446655440000',
      sequence_number: 3,
      title: 'Database Integrations & Row Level Security',
      description: 'Setup Supabase client connections, model relational structures, write PostgreSQL triggers, and write RLS policies.',
      estimated_days: 7,
      topics: ['Supabase Client wrapper hooks', 'Postgres queries schema', 'RLS policies config', 'Trigger triggers'],
      learning_objectives: ['Query remote SQL databases', 'Audit triggers execution', 'Secure tables via personal auth tags'],
      status: 'not_started',
    },
    {
      id: 'mile_4',
      user_id: MOCK_USER.id,
      roadmap_id: '550e8400-e29b-41d4-a716-446655440000',
      sequence_number: 4,
      title: 'LLM Orchestration & Context Chains',
      description: 'Connect Google Gemini SDK, create prompts structure helpers, parse outputs JSONs, and cache API tokens.',
      estimated_days: 7,
      topics: ['Gemini 1.5 Pro SDK models', 'Zero-shot prompt scopes', 'JSON parse error falls', 'Caching setups'],
      learning_objectives: ['Generate structured JSON outputs', 'Verify prompt model inputs', 'Build API retry logic controllers'],
      status: 'not_started',
    },
    {
      id: 'mile_5',
      user_id: MOCK_USER.id,
      roadmap_id: '550e8400-e29b-41d4-a716-446655440000',
      sequence_number: 5,
      title: 'Deployment pipelines & Docker Scaffolds',
      description: 'Dockerize local servers, mount environment files, register GitHub action workflows, and deploy on Railway.',
      estimated_days: 7,
      topics: ['Dockerfile layers compilation', 'GitHub Actions setup', 'API CORS configs', 'Environment vars verification'],
      learning_objectives: ['Package build files inside images', 'Automate CI checks triggers', 'Audit logs on Railway ports'],
      status: 'not_started',
    },
  ],
};

export const MOCK_TASKS: Task[] = [
  // Completed yesterday's tasks (Day 6 of Milestone 1)
  {
    id: 'task_001',
    user_id: MOCK_USER.id,
    roadmap_id: MOCK_ROADMAP.id,
    milestone_id: 'mile_1',
    day_number: 6,
    task_date: '2026-07-16',
    title: 'Analyze Module Systems differences (CommonJS vs. ESM)',
    description: 'Read TypeScript documentation on target outputs, node resolution strategies, and import formats.',
    task_type: 'Read',
    estimated_minutes: 30,
    is_completed: true,
    completed_at: '2026-07-16T14:22:00Z',
    resource_id: 'res_1_1',
  },
  // Today's tasks (Day 1 of Milestone 2)
  {
    id: 'task_002',
    user_id: MOCK_USER.id,
    roadmap_id: MOCK_ROADMAP.id,
    milestone_id: 'mile_2',
    day_number: 7,
    task_date: '2026-07-17',
    title: 'Express Server setup with TypeScript typings',
    description: 'Scaffold basic App routers, type Express Request-Response handlers, and test health endpoints.',
    task_type: 'Build',
    estimated_minutes: 45,
    is_completed: false,
    resource_id: 'res_2_1',
  },
  {
    id: 'task_003',
    user_id: MOCK_USER.id,
    roadmap_id: MOCK_ROADMAP.id,
    milestone_id: 'mile_2',
    day_number: 7,
    task_date: '2026-07-17',
    title: 'Integrate standard Express middleware routing handlers',
    description: 'Learn request cycles, set up cors parameters, and write a global logging middleware.',
    task_type: 'Watch',
    estimated_minutes: 20,
    is_completed: false,
    resource_id: 'res_2_2',
  },
  {
    id: 'task_004',
    user_id: MOCK_USER.id,
    roadmap_id: MOCK_ROADMAP.id,
    milestone_id: 'mile_2',
    day_number: 7,
    task_date: '2026-07-17',
    title: 'Express router routing configurations quiz',
    description: 'Verify understanding of router middlewares chains, response codes, and exception boundaries.',
    task_type: 'Quiz',
    estimated_minutes: 15,
    is_completed: false,
    resource_id: 'res_2_3',
  },
];

export const MOCK_RESOURCES: Resource[] = [
  // Milestone 1 Resources
  {
    id: 'res_1_1',
    user_id: MOCK_USER.id,
    milestone_id: 'mile_1',
    topic: 'tsconfig configurations',
    title: 'TypeScript TSConfig.json Guide',
    url: 'https://www.typescriptlang.org/docs/handbook/tsconfig-json.html',
    resource_type: 'Documentation',
    estimated_minutes: 25,
    difficulty: 'beginner',
    why_recommended: 'Official comprehensive parameters guidelines from standard TS handbook.',
    is_bookmarked: true,
  },
  // Milestone 2 Resources
  {
    id: 'res_2_1',
    user_id: MOCK_USER.id,
    milestone_id: 'mile_2',
    topic: 'Express Server setup with TypeScript typings',
    title: 'How to Setup Express with TypeScript',
    url: 'https://dev.to/alok722/how-to-setup-express-with-typescript-379a',
    resource_type: 'Article',
    estimated_minutes: 15,
    difficulty: 'intermediate',
    why_recommended: 'Step-by-step walk-through to compile typescript routes files in Node.',
    is_bookmarked: false,
  },
  {
    id: 'res_2_2',
    user_id: MOCK_USER.id,
    milestone_id: 'mile_2',
    topic: 'Express Middleware pipelines',
    title: 'Express Middleware Explained simply',
    url: 'https://www.youtube.com/watch?v=lY6icfhap2o',
    resource_type: 'Video',
    estimated_minutes: 18,
    difficulty: 'beginner',
    why_recommended: 'Excellent visual representation of input routing middleware chains.',
    is_bookmarked: false,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj_1',
    user_id: MOCK_USER.id,
    milestone_id: 'mile_1',
    title: 'TypeScript Compiler CLI Packager',
    description: 'Construct a command line interface utility that scans workspace configuration options and generates structural build bundle logs.',
    objective: 'Test compiler flags configuration and project directory compilation checks.',
    tech_stack: ['NodeJS', 'TypeScript', 'Yargs/Commander'],
    deliverable: 'GitHub Repository containing clean source folders, customized tsconfig parameters, and executable CLI entry scripts.',
    estimated_hours: 4,
    status: 'completed',
    started_at: '2026-07-15T09:00:00Z',
    completed_at: '2026-07-16T17:00:00Z',
    steps: [
      {
        step_number: 1,
        title: 'Project structure initialization',
        description: 'Initialize npm workspace package folders and install typescript dev dependencies.',
        hint: 'Use ts-node directly during engineering trials but verify outputs match raw javascript build configs.',
        hint_revealed: true,
      },
      {
        step_number: 2,
        title: 'TSConfig Strict check config',
        description: 'Toggle noImplicitAny and strictNullChecks to true, resolving initial compile discrepancies.',
        hint: 'Enforce target as ES2022 to enable native promise chains support.',
        hint_revealed: false,
      },
    ],
    qa_history: [
      {
        role: 'user',
        message: 'Why does TSC throw compilation modules errors on ES2022 syntax declarations?',
        timestamp: '2026-07-15T10:12:00Z',
      },
      {
        role: 'assistant',
        message: 'Ensure your compiler options config array includes ESNext or ES2022 targets inside lib parameter keys. Check the "moduleResolution" parameter as well.',
        timestamp: '2026-07-15T10:13:00Z',
      },
    ],
  },
  {
    id: 'proj_2',
    user_id: MOCK_USER.id,
    milestone_id: 'mile_2',
    title: 'Zod validated API User Directory Controller',
    description: 'Build a secure local API router framework that parses payloads, matches models against validation rules, and forwards clean objects to controllers.',
    objective: 'Construct Express middleware loops running Zod checking models.',
    tech_stack: ['NodeJS', 'ExpressTS', 'Zod schema validations'],
    deliverable: 'Running test server endpoint maps validating body and query parameters.',
    estimated_hours: 6,
    status: 'in_progress',
    started_at: '2026-07-17T09:00:00Z',
    steps: [
      {
        step_number: 1,
        title: 'App router scaffolding setup',
        description: 'Scaffold routing paths inside a separate router handler file.',
        hint: 'Avoid standard app.post bindings; delegate routes into route groups.',
      },
      {
        step_number: 2,
        title: 'Formulating the validation middleware',
        description: 'Create middleware functions capturing req.body and evaluating Zod results.',
        hint: 'If parsing fails, intercept request cycles immediately, reporting HTTP 400 Bad Request.',
      },
    ],
    qa_history: [],
  },
];

export const MOCK_PROGRESS: Progress = {
  id: 'prog_1',
  user_id: MOCK_USER.id,
  roadmap_id: MOCK_ROADMAP.id,
  total_tasks: 25,
  completed_tasks: 6,
  completion_percentage: 24.0,
  current_streak: 5,
  longest_streak: 9,
  last_activity_date: '2026-07-17',
  total_milestones: 5,
  completed_milestones: 1,
  activity_log: [
    { date: '2026-07-12', tasks_completed: 1, minutes_spent: 30 },
    { date: '2026-07-13', tasks_completed: 2, minutes_spent: 45 },
    { date: '2026-07-14', tasks_completed: 1, minutes_spent: 20 },
    { date: '2026-07-15', tasks_completed: 1, minutes_spent: 40 },
    { date: '2026-07-16', tasks_completed: 1, minutes_spent: 30 },
  ],
};
